@vite([
    'resources/css/style.css',
    'resources/css/media_style.css',
    'resources/css/product_style.css',
    'resources/css/category_style.css',
    'resources/css/login_style.css',
    'resources/css/basket_style.css',
    'resources/css/footer_style.css',
    'resources/css/carousel.css',
    'resources/css/bootstrap.css'
])
